{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 40,
      "metadata": {
        "id": "a9ykxM_mW7yx"
      },
      "outputs": [],
      "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from keras.datasets import cifar10\n",
        "from keras.utils import to_categorical\n",
        "from keras.models import Sequential\n",
        "from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense\n",
        "import tensorflow as tf\n",
        "from PIL import Image\n",
        "import matplotlib.pyplot as plt\n",
        "from tensorflow.keras.preprocessing import image"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Load the CIFAR-10 dataset\n",
        "(x_train, y_train), (x_test, y_test) = cifar10.load_data()"
      ],
      "metadata": {
        "id": "4lBnGhNLZz70"
      },
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "x_train.shape[1:]"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "HYtmcs6IcRtN",
        "outputId": "1357667b-933f-4799-bf08-8154958490a6"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(32, 32, 3)"
            ]
          },
          "metadata": {},
          "execution_count": 3
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Preprocess the data\n",
        "x_train = x_train.astype('float32') / 255\n",
        "x_test = x_test.astype('float32') / 255\n",
        "y_train = to_categorical(y_train, num_classes=10)\n",
        "y_test = to_categorical(y_test, num_classes=10)"
      ],
      "metadata": {
        "id": "IjkdtHjKZ3cC"
      },
      "execution_count": 4,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**Using hyperparameter tuning**"
      ],
      "metadata": {
        "id": "AYcW1nXQ0c-m"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Define the model function\n",
        "def create_model(learning_rate=0.001, num_filters=32, kernel_size=(3,3), activation='relu', optimizer='adam'):\n",
        "    model = Sequential()\n",
        "    model.add(Conv2D(num_filters, kernel_size, activation=activation, input_shape=x_train.shape[1:]))\n",
        "    model.add(MaxPooling2D((2, 2)))\n",
        "    model.add(Conv2D(num_filters*2, kernel_size, activation=activation))\n",
        "    model.add(MaxPooling2D((2, 2)))\n",
        "    model.add(Conv2D(num_filters*4, kernel_size, activation=activation))\n",
        "    model.add(MaxPooling2D((2, 2)))\n",
        "    model.add(Flatten())\n",
        "    model.add(Dense(64, activation=activation))\n",
        "    model.add(Dense(10, activation='softmax'))\n",
        "    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])\n",
        "    return model"
      ],
      "metadata": {
        "id": "vIV08pT6XltY"
      },
      "execution_count": 5,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from tensorflow.keras.wrappers.scikit_learn import KerasClassifier"
      ],
      "metadata": {
        "id": "EyMEIAWDXuiP"
      },
      "execution_count": 7,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Create the KerasClassifier object\n",
        "model = KerasClassifier(build_fn=create_model, verbose=0)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "11tyH7BDXo5y",
        "outputId": "241e3919-8998-487e-f063-2a3fcf60758e"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "<ipython-input-8-6b65e3158d86>:2: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
            "  model = KerasClassifier(build_fn=create_model, verbose=0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Define the hyperparameters to tune\n",
        "param_grid = {'learning_rate': [0.001, 0.01],\n",
        "              'num_filters': [32, 64],\n",
        "              'kernel_size': [(3, 3), (5, 5)],\n",
        "              'activation': ['relu', 'tanh'],\n",
        "              'optimizer': ['adam', 'rmsprop']}"
      ],
      "metadata": {
        "id": "sv2QyCvwXwBh"
      },
      "execution_count": 9,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.model_selection import GridSearchCV"
      ],
      "metadata": {
        "id": "ebSjB0ZOX2mG"
      },
      "execution_count": 10,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Perform grid search cross-validation\n",
        "grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)\n",
        "grid_result = grid.fit(x_train, y_train)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "G3deOPGxXysY",
        "outputId": "45796e64-f980-4041-abfb-7ef188e026a9"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: \n",
            "48 fits failed out of a total of 96.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_38\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_38/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_38\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_41\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_41/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_41\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_44\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_44/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_44\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_47\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_47/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_47\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_50\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_50/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_50\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_53\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_53/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_53\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_56\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_56/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_56\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_59\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_59/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_59\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_62\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_62/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_62\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_65\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_65/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_65\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_68\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_68/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_68\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_71\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_71/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_71\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_74\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_74/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_74\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_77\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_77/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_77\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_80\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_80/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_80\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_83\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_83/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_83\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_86\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_86/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_86\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_89\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_89/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_89\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_92\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_92/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_92\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_95\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_95/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_95\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_98\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_98/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_98\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_101\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_101/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_101\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "2 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_104\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_104/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_104\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_107\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_107/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_107\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_71\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_71/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_71\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_89\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_89/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_89\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_107\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_107/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_107\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_110\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_110/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_110\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_113\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_113/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_113\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_116\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_116/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_116\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_119\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_119/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_119\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_122\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_122/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,128].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_122\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_125\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_125/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_125\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_128\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_128/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_128\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_131\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_131/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_131\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_134\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_134/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_134\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_137\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_137/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_137\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
            "    return super().fit(x, y, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
            "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
            "  File \"<ipython-input-5-bc3e226d8efa>\", line 9, in create_model\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n",
            "    result = method(self, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py\", line 1967, in _create_c_op\n",
            "    raise ValueError(e.message)\n",
            "ValueError: Exception encountered when calling layer \"max_pooling2d_140\" (type MaxPooling2D).\n",
            "\n",
            "Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_140/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 2, 2, 1], padding=\"VALID\", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,256].\n",
            "\n",
            "Call arguments received by layer \"max_pooling2d_140\" (type MaxPooling2D):\n",
            "  â€¢ inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float32)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.49117949 0.4600605  0.53628002 0.50840045 0.50297998 0.49486028\n",
            " 0.54298013 0.50306024        nan        nan        nan        nan\n",
            "        nan        nan        nan        nan 0.56175991 0.54331986\n",
            " 0.5595397  0.53295952 0.56387989 0.5623198  0.57777981 0.5522398\n",
            "        nan        nan        nan        nan        nan        nan\n",
            "        nan        nan]\n",
            "  warnings.warn(\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Print the best results\n",
        "print(f'Best accuracy: {grid_result.best_score_:.4f} using {grid_result.best_params_}')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "OgAnZrZxvROv",
        "outputId": "167304c2-f013-4ab3-8d67-d4311836f618"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Best accuracy: 0.5778 using {'activation': 'tanh', 'kernel_size': (3, 3), 'learning_rate': 0.01, 'num_filters': 64, 'optimizer': 'adam'}\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Evaluate the model on the test set\n",
        "test_loss, test_acc = grid_result.best_estimator_.model.evaluate(x_test, y_test)\n",
        "print(f'Test accuracy: {test_acc:.4f}')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bsCJlutzvVLd",
        "outputId": "2fc657b7-ca5f-47e3-fcf5-e5770da98fb1"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "313/313 [==============================] - 12s 39ms/step - loss: 1.1467 - accuracy: 0.5933\n",
            "Test accuracy: 0.5933\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**Without hyper parameter tuning**"
      ],
      "metadata": {
        "id": "9i05eZ1E0muT"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Create the CNN model\n",
        "model = Sequential()\n",
        "model.add(Conv2D(32, (3, 3), activation='relu', input_shape=x_train.shape[1:]))\n",
        "model.add(MaxPooling2D((2, 2)))\n",
        "model.add(Conv2D(64, (3, 3), activation='relu'))\n",
        "model.add(MaxPooling2D((2, 2)))\n",
        "model.add(Conv2D(128, (3, 3), activation='relu'))\n",
        "model.add(MaxPooling2D((2, 2)))\n",
        "model.add(Flatten())\n",
        "model.add(Dense(64, activation='relu'))\n",
        "model.add(Dense(10, activation='softmax'))"
      ],
      "metadata": {
        "id": "-pVCaIlTaArM"
      },
      "execution_count": 14,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Compile the model\n",
        "model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])"
      ],
      "metadata": {
        "id": "906PZ-jaany6"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Train the model\n",
        "history = model.fit(x_train, y_train, epochs=10, batch_size=64, validation_data=(x_test, y_test))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "wnLctIjSSfwz",
        "outputId": "0431cb14-b297-4fdd-deca-14861321f99d"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Epoch 1/10\n",
            "782/782 [==============================] - 87s 110ms/step - loss: 1.5903 - accuracy: 0.4179 - val_loss: 1.3314 - val_accuracy: 0.5212\n",
            "Epoch 2/10\n",
            "782/782 [==============================] - 85s 108ms/step - loss: 1.2101 - accuracy: 0.5713 - val_loss: 1.1062 - val_accuracy: 0.6121\n",
            "Epoch 3/10\n",
            "782/782 [==============================] - 85s 109ms/step - loss: 1.0579 - accuracy: 0.6305 - val_loss: 1.0076 - val_accuracy: 0.6445\n",
            "Epoch 4/10\n",
            "782/782 [==============================] - 86s 110ms/step - loss: 0.9494 - accuracy: 0.6689 - val_loss: 0.9635 - val_accuracy: 0.6682\n",
            "Epoch 5/10\n",
            "782/782 [==============================] - 83s 106ms/step - loss: 0.8720 - accuracy: 0.6964 - val_loss: 0.9568 - val_accuracy: 0.6692\n",
            "Epoch 6/10\n",
            "782/782 [==============================] - 83s 107ms/step - loss: 0.8062 - accuracy: 0.7196 - val_loss: 0.9028 - val_accuracy: 0.6877\n",
            "Epoch 7/10\n",
            "782/782 [==============================] - 84s 107ms/step - loss: 0.7473 - accuracy: 0.7409 - val_loss: 0.8760 - val_accuracy: 0.6950\n",
            "Epoch 8/10\n",
            "782/782 [==============================] - 85s 109ms/step - loss: 0.6944 - accuracy: 0.7570 - val_loss: 0.8994 - val_accuracy: 0.6971\n",
            "Epoch 9/10\n",
            "782/782 [==============================] - 85s 108ms/step - loss: 0.6494 - accuracy: 0.7730 - val_loss: 0.8847 - val_accuracy: 0.6992\n",
            "Epoch 10/10\n",
            "782/782 [==============================] - 84s 107ms/step - loss: 0.6131 - accuracy: 0.7836 - val_loss: 0.8670 - val_accuracy: 0.7148\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Save the model to a file\n",
        "model.save('cifar10_model.h5')"
      ],
      "metadata": {
        "id": "En_yguaG9VuE"
      },
      "execution_count": 17,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Load the saved model\n",
        "model = tf.keras.models.load_model('cifar10_model.h5')"
      ],
      "metadata": {
        "id": "fZUumSzW9a77"
      },
      "execution_count": 20,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Load the CIFAR-10 class names\n",
        "class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']"
      ],
      "metadata": {
        "id": "DF3pClTP9pvE"
      },
      "execution_count": 21,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Select a random test image\n",
        "index = np.random.randint(len(x_test))\n",
        "test_image = x_test[index]\n",
        "expected_class = np.argmax(y_test[index])"
      ],
      "metadata": {
        "id": "erbndK5z9s2S"
      },
      "execution_count": 22,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Make a prediction\n",
        "predicted_class = np.argmax(model.predict(np.array([test_image])))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vvn-B9cM9yUS",
        "outputId": "87f64855-6d0d-4e8b-9fcd-be498bf820be"
      },
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "1/1 [==============================] - 0s 162ms/step\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Print the result\n",
        "print('Expected class:', class_names[expected_class])\n",
        "print('Predicted class:', class_names[predicted_class])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4g6ggXyW91zs",
        "outputId": "9c05181f-f1a5-4b87-ac03-ffcc9bb3f4f0"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Expected class: frog\n",
            "Predicted class: frog\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Evaluate the model on the test set\n",
        "test_loss, test_acc = model.evaluate(x_test, y_test)\n",
        "print('Test accuracy:', test_acc)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "PsnyIr7wWUXz",
        "outputId": "57766278-95ce-4dbb-90ff-986696dc80dd"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "313/313 [==============================] - 6s 19ms/step - loss: 0.8670 - accuracy: 0.7148\n",
            "Test accuracy: 0.7148000001907349\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Load and preprocess the image\n",
        "img = image.load_img('frog.jpeg', target_size=(32, 32))\n",
        "img_array = image.img_to_array(img)\n",
        "img_array = np.expand_dims(img_array, axis=0)\n",
        "img_array /= 255.\n",
        "\n",
        "# Predict the class of the image\n",
        "prediction = model.predict(img_array)\n",
        "class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']\n",
        "predicted_class = class_names[np.argmax(prediction)]\n",
        "\n",
        "# Show the predicted image and class\n",
        "fig, ax = plt.subplots(figsize=(8, 8))\n",
        "ax.imshow(img_array[0])\n",
        "ax.set_title('Predicted class: ' + predicted_class)\n",
        "ax.axis('off')\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 500
        },
        "id": "5Ok7Qrx3ABrn",
        "outputId": "e612da32-e661-46ca-d807-53a0ae7e239c"
      },
      "execution_count": 44,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "1/1 [==============================] - 0s 27ms/step\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 576x576 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAcEAAAHRCAYAAAASbQJzAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAViUlEQVR4nO3debTmdX3Y8c9ndmZn2NchVkAUPWgQY9zSHBOTuAVtBYxJNamJ1jZtDsVEmqilBnPapCZUPSJt1AZbt1iketBG7VEMrjESwo4gMAyzMDvDDLPcb/+4v2lv53AHfl9hFj6v1zkch/s8n/v5PY+Xec/z3Du/X7bWAgAqmnGgDwAADhQRBKAsEQSgLBEEoCwRBKAsEQSgLBGklMz8aGa+Z/j1izLz1v20t2XmU0fO/Exmrniijukx7D8mM7+emVsy808O1HHAE0kEOehk5o8yc1tmPpiZq4dwLXy897TWrm2tnf4YjueNmfmNx3v/IeA3I+KBiFjcWrvwQB8MPBFEkIPVK1trCyPiORFxdkT8/t53yMxZ+/2oalkeETe1ac6o4fnnyUAEOai11u6LiGsi4syI//u24tsy8/aIuH342Csy8weZuTEzr8vMZ+2Zz8xnZ+b3h7f0PhkR86bc9v+93ZiZJ2XmZzNzbWauy8z3Z+YZEfGhiHj+8Mp043DfuZn5x5l5z/Bq9UOZediUz3VRZt6fmSsz89f39Rgzc1lmfmS474bMvGqa+/1eZv5weCw3Zea5U257amZ+LTM3ZeYDw2ONnPS+zFyTmZsz84bMPPPRnvfM/GhE/JOIePvwuF+ame/OzM9k5pWZuTki3piZx2fm1Zm5PjPvyMw3T/kch2Xmx4bHdHNmvv1Avr0Lj0QEOahl5kkR8UsR8bdTPvzLEfG8iHh6Zj47Iv48In4rIo6IiMsj4uohUnMi4qqI+IuIWBYRn46I106zZ2ZEfD4i7o6IUyLihIj4RGvt5oh4S0R8s7W2sLW2dBj5o4g4LSLOioinDvd/5/C5fiEi/nVE/FxEnBoRL32Uh/kXETE/Ip4REUdHxPumud8PI+JFEbEkIv5tRFyZmccNt/27iPhfEXF4RJwYEf9p+PjPR8SLh2NdEhGvi4h1w3G+PjP/7pEWtdbeGBEfj4h/PzzuLw83vToiPhMRS4fbPxERKyLi+Ij4RxFxaWb+7HDfd8Xkc/mU4bl4w6M8D7DfiSAHq6uGV13fiIivRcSlU257b2ttfWttW0x+3+ry1tq3W2u7W2sfi4iHI+Knhn9mR8SfttZ2ttY+ExHfnWbfOTH5G/lFrbWtrbXtrbVH/D5gZuaw93eG49gyHN/5w11eFxEfaa39fWtta0S8e7oHOUTsFyPiLa21DcNxfu2R7tta+3RrbWVrbaK19smYfCV8znDzzph8+/L4vY59Z0QsioinRUS21m5urd0/fL7/1lp7VozzzdbaVa21iYg4MiJeEBG/O+z8QUT854j4tSnPw6XD41oREZeN3AVPOBHkYPXLrbWlrbXlrbV/NgRvj3un/Hp5RFw4vBW6cQjnSTEZtOMj4r69vqd19zT7ToqIu1trux7DsR0Vk6/c/mbKzi8OH49h79RjnG7nnr3rW2sbHm1pZv7alLd9N8bkW8RHDje/PSIyIr6TmTfueQu2tfbViHh/RHwgItZk5oczc/FjeIzTmfq4jh+OfcuUj90dk6+K99w+9f5Tfw0HBRHkUDQ1avdGxB8Owdzzz/zW2n+PiPsj4oThldseJ0/zOe+NiJOn+WGPvX8w5IGI2BYRz5iyc8nwgzwx7D3pMezcs3dZZi7dx30iM5dHxBUR8c8j4ojhbdm/j8nwRWttVWvtza2142PyreEP7vkrGa21y1prPxkRT4/Jt0Uv2teuRzH1uVg5HPuiKR87OSLuG359f0y+NbvH1OcEDgoiyKHuioh4S2Y+b/ghkAWZ+fLhN+ZvRsSuiPjtzJydma+J//f24d6+E5O/af/R8DnmZeYLhttWR8SJw/cYY3gr8IqIeF9mHh0RkZknZObLhvt/KiZ/aOTpmTk/Jr839oiGtyavicloHT4c54sf4a4LYjJAa4d9b4rhh4WGf//HmbknOBuG+05k5nOH52Z2RGyNiO0RMTHd8YzRWrs3Iq6LiPcOz9ezIuI3IuLK4S6fioh3DI/rhJgMOBxURJBDWmvtexHx5ph8y29DRNwREW8cbtsREa8Z/n19RJwXEZ+d5vPsjohXxuQPudwTkz/scd5w81cj4saIWJWZDwwf+91h17eGn5T8ckScPnyuayLiT4e5O4b/3Zdfjcnv3d0SEWsi4l89wvHdFBF/EpNhXx0Rz4yIv55yl+dGxLcz88GIuDoi/mVr7c6IWByTwd4Qk29VrouI/xARkZm/kpk3PsqxPZoLYvKHX1ZGxP+IiHdN+SGaS2LyebwrJp+fz8Tk92vhoJEuqgvsD5n51og4v7X2kgN9LLCHV4LAEyIzj8vMF2TmjMw8PSIujMlXi3DQcMYH4IkyJyb/3uZPRMTGmPw7hR88kAcEe/N2KABleTsUgLJEEICyHu17gt4rBeBQl9Pd4JUgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGXNOtAHwONrYvf20TNv/e1/2LXr8g9c2zXnyw44WHglCEBZIghAWSIIQFkiCEBZIghAWSIIQFkiCEBZIghAWSIIQFkiCEBZIghAWSIIQFkiCEBZ2Vrb1+37vJEnzrV/fU3X3HXfunL0zJmnPa1r10f//BNdc0vnzB09c8Unv9K1K+LwzjngSSSnu8ErQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMpyAu2D1BvOXdI1t2LV5tEzxx59VNeuL/3Vzq65JYsWjJ554c+d07XriGW3jp75s8tu7NoFHLScQBsA9iaCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlDXrQB9ACRO7R4+ccFjfFRqOPnP8zKaHdnTtOu7oTV1z23L8l91LX/bUrl2zZo4/xksu/emuXe+8+LquOeDA8UoQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJcRWI/2D2jjZ459qiXdO06atlDo2fmHj+7a9cznru9a+6yS68fPbP5/v/dtWv1ytWjZ4572gldu/7NJc8dPfOH7/xu1y7g8eGVIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGVla/s8ufP4Mz/zuNjdOfelj39g9Mz6u67r2nXrreNPTh0RceF7f3P0zFt/6/e7dr3qdS8aPbMr1nbtuuvuNaNnTj31jK5dF1zwka45KCqnu8ErQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKchUJ4pufu7JrbtPWB7rmHtw1/goIT1k+/soTERHX3/G50TPbdq7r2nX0kctHz9x+26auXROz+o7xTed9YfTM8ctP6NoFBxFXkQCAvYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABlOYE28YW//HDX3MTW9V1zm1ZdP3rm5nVf6dq1+IhjRs/8zE+/sGvXzXeMPxn2gsWzu3ZtWNd38vK1m24bPTN77vO6dr39X/SdmB2eAE6gDQB7E0EAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKchUJYmJiomvuc1e8p2vuiKOXjJ55cMtfde26b+0to2fOevbLu3Z98Xt/M3pm0dzxz0VExNJlc7vmVq+9c/TMnNl9f1beOePI0TMXve0LXbsy+q7GQRmuIgEAexNBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKcgJtul39sT/rmpsXu0bPZNzbtWvDuu+Onpm7dHnXrrvWrh6/a8kZXbsWLtzcNXfyiWeOntm688auXT+667bRMxu3LO3adfGF13TNUYYTaAPA3kQQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJEEICyRBCAsmYd6APg0LVt+/auuYd3bBw9M3t235fq7Iklo2e2rDyha9frL3jF6Jl3XPwHXbt+7z0Xd83dc88to2dWrVrZtevkk44YPTN7fd/X1I5dG7rm5sw6vGuOJw+vBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoK1tr+7p9nzdCj0996I9Hz8zYeWfXrl0bbh49s3rT+CstREQcd8rxo2d+8WW/07Xrroce7pr7wY1/OXpm5uw1XbsOm/ec0TM547auXesf7Pvz/G+c/9WuOQ45Od0NXgkCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlhNos9/918suGT0zM3d27Wqb7h49s271tV278ogto2eWHfvCrl3nvvL1XXPXrxh/Muwbbv2fXbuOOHracxZPa/vmlV275sw5smtu94z5o2cueNXnu3ZxQDmBNgDsTQQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoy1Uk2O8eWLdq9MxVH3l/1662a2L0zI41t3TtmpE3jJ459pyFXbtWb/qprrlfesX5o2e+/f0Pdu3a0cZfsWKi7ejatXjurK65aEtGj6x4YF3Xqre9oefqJJ2vU8Z/2f9Y6w4BriIBAHsTQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAyhJBAMoSQQDKEkEAynICbfa7Sy98zeiZh3f2/Xlt4cJlo2fWrFnftWv5vK2jZxaePv4k0xERC489tWtu8/aHR88cuXR2166ds8fvmpHbunbFxPausYc2dpx4+7A5Xbt2PXTC6Jl77/161662Y1fX3MV/cNfomZldm/Y7J9AGgL2JIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGV1nEIdfjyrvv/50TMP7j6la9cZLzp79MzChfO6dt1+7+rRMycfvqpr10mnvKBr7pgjd4ye2bKr72IyD2/eMnpm28xFXbu+9sWPd80dd8xzRs/saH/btWvpsiNHzyw+vO/5WDz/KV1zsXv3+JmZh8h1JKbhlSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZYkgAGWJIABliSAAZbmKBPtdmzH+zPhLc07XrvVr14+eWbDgsK5dc+bcMHpm/YN9V2hYtuDUrrnWfjR6ZvvOvmPcsGX8VSSu+/L1XbsWHNX39fHgw7eOnjn2mKO6di1ZOnv0zKmnndm1a/2G8Vc0iYiYOePQviJED68EAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKMsJtNnvdu4cfyLhJUvnd+265MNfGD3zjn/6sq5dc8efFzzOef5ZXbtW3L22a27h0mNHzyxaMK9r187VG8YP7bina9fS+cu65hYdP34ud/edUPwnnrJ89MztN32ra9fDK87tmouX940dyrwSBKAsEQSgLBEEoCwRBKAsEQSgLBEEoCwRBKAsEQSgLBEEoCwRBKAsEQSgLBEEoCwRBKAsV5GgW9+59CM2btk8eubkf7C4a9eMiZmjZ+6+7cauXc/8yQWjZ5Ysmtu16877tnfNPbgjR8/c9qPbu3Z97xvfGz1z9BFbu3YdvuS0rrkdO3eMnjn77JO7dn3l6q+Pnjnr7F/v2vX0c1/bNTcxMTF6JnP819SPM/d480oQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJEEICyRBCAskQQgLJEEICyRBCAspxAm9jdObf27pu75ubumjd65q7Va7t2veaF4092/KrzzuvatXrVp0bPLJ79nK5dP7jh1q65xUuWjZ5ZseKerl1bt+0aPTN/xlldu2JX34nITz9t/PNx/XdWdO160TPeNXrmhpv6vu5f/aqzu+Z6Tmp9sJwIu5dXggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUla21fd2+zxs5+Fz90fePnll14ze6dj0054Guufvumjl6ZsmxN3btemDd1tEzK1du7Nr1pjf96uiZbZvO6Nr1Hy//L11zq9aM//9s8fzDunZt2DL+KhJHLXq4a9dLXrmwa27e7AWjZ45cdG7Xrs1bJ0bPXPTu93Ttmjdv/JVanuSmvdSFV4IAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlOUqEk8y27ZsHj3z6cvf17Vrw8ofds2d+qzxZ7j/u1u/37XrxBNPGT0zc+b4q1xERMzZduLomXNe/ZauXbPm9V3ZYc2aNaNnrv3sh7p23bbyS6Nnznzm87t23XnL/K65s1/8s6NnXnv+r3Ttypz2QgY88VxFAgD2JoIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJTlBNrsd7u2bx0903vC6N0df86b6NoUMWvf/y09ov19UuXdu3ePnmk7tnXtyrkLR8/M6P1jecdzH+Gk1oU4gTYA7E0EAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKEsEAShLBAEoSwQBKMtVJAB4snMVCQDYmwgCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUJYIAlCWCAJQlggCUNasR7k998tRAMAB4JUgAGWJIABliSAAZYkgAGWJIABliSAAZf0f2kcxQ2/ZFHwAAAAASUVORK5CYII=\n"
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Plot the training and validation accuracy over time\n",
        "plt.plot(history.history['accuracy'], label='training accuracy')\n",
        "plt.plot(history.history['val_accuracy'], label='validation accuracy')\n",
        "plt.legend()\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 268
        },
        "id": "1BosvQfkWbsz",
        "outputId": "f6b5b128-b1d9-4426-f709-2da40384f97b"
      },
      "execution_count": 45,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAD7CAYAAABkO19ZAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAAsTAAALEwEAmpwYAAA4KklEQVR4nO3deVzVddr/8dfFDorIIi4gguaWuKC4m2lmapllVpo2ZXfpjK0z/WappqnG7mmauZtq7ntqJiubGjVzNEubynTKMVMJcN9ScWFzQVAEZDucz++Pc8QjghzhwIHD9Xw8eMh3+3CdI7z58l2urxhjUEop5bm83F2AUkqphqVBr5RSHk6DXimlPJwGvVJKeTgNeqWU8nAa9Eop5eGcCnoRmSgiP4jIIRF5qprlMSLyjYhsE5GdInKzw7Kn7dv9ICITXFm8Ukqp2klt19GLiDdwABgPZALJwD3GmL0O6ywAthlj/ioi1wKfG2Ni7Z9/CAwBOgHrgB7GmIoGeTVKKaUu4+PEOkOAQ8aYwwAishS4DdjrsI4B2tg/DwGy7Z/fBiw1xpQCR0TkkH28zTV9sYiICBMbG3s1r0EppVq81NTU08aYdtUtcyboo4AMh+lMYGiVdV4AvhKRx4BWwI0O226psm1U1S8gInOBuQAxMTGkpKQ4UZZSSqkLRORYTctcdTL2HuDvxpho4GbgHyLi9NjGmAXGmERjTGK7dtX+QlJKKVVHzuzRZwGdHaaj7fMcPQhMBDDGbBaRACDCyW2VUko1IGf2upOB7iISJyJ+wAxgVZV10oFxACLSGwgAcuzrzRARfxGJA7oD37uqeKWUUrWrdY/eGGMRkUeBNYA3sNAYs0dE5gMpxphVwP8D3haRn2E7MTvb2C7n2SMiy7CduLUAj9Tlipvy8nIyMzMpKSm52k2VhwoICCA6OhpfX193l6JUk1fr5ZWNLTEx0VQ9GXvkyBGCg4MJDw9HRNxUmWoqjDHk5uZSUFBAXFycu8tRqkkQkVRjTGJ1y5rFnbElJSUa8qqSiBAeHq5/4SnlpGYR9ICGvLqEfj8o5TxnrrpRSinVAIwx5BSWcvBkIQdOFuDn48WsoV1c/nU06J1w9uxZlixZwsMPP3zV2958880sWbKEtm3b1rjOc889x+jRo7nxxhtrXEcp1bzlFpZy4GQhB08VcOBkAQfs4X72fHnlOgkxbTXo3eXs2bO8+eab1Qa9xWLBx6fmt/Hzzz+vdfz58+fXqz53qO11K9VS5Z8v58CpAn44UcBBe6AfPFXA6cKyynWCA3zo0T6YSfEd6NE+mB7tg+nevjXtWvs3SE36k+qEp556irS0NAYMGMD48eO55ZZb+M1vfkNoaCj79+/nwIED3H777WRkZFBSUsITTzzB3LlzAYiNjSUlJYXCwkImTZrEqFGj2LRpE1FRUXz66acEBgYye/ZsJk+ezJ133klsbCz3338/q1evpry8nH/+85/06tWLnJwcZs6cSXZ2NsOHD2ft2rWkpqYSERFxSa3z5s0jOTmZ4uJi7rzzTn77298CkJyczBNPPEFRURH+/v78+9//JigoiF/96ld8+eWXeHl5MWfOHB577LHKmiMiIkhJSeHnP/8569ev54UXXiAtLY3Dhw8TExPD73//e370ox9RVFQEwF/+8hdGjBgBwB/+8AcWLVqEl5cXkyZNYs6cOdx1111s3boVgIMHDzJ9+vTKaaWam3Ml5Rw8WcjBkwX8cLKg8vDLqYLSynVa+XnTvX0wN/SKtId5MD3bB9O+jX+jnmdqdkH/29V72Jt9zqVjXtupDc/f2qfG5S+//DK7d+9m+/btAKxfv56tW7eye/fuysv7Fi5cSFhYGMXFxQwePJhp06YRHh5+yTgHDx7kww8/5O233+buu+9mxYoV3HvvvZd9vYiICLZu3cqbb77JK6+8wjvvvMNvf/tbbrjhBp5++mm+/PJL3n333Wpr/d3vfkdYWBgVFRWMGzeOnTt30qtXL6ZPn85HH33E4MGDOXfuHIGBgSxYsICjR4+yfft2fHx8yMvLq/W92rt3Lxs3biQwMJDz58+zdu1aAgICOHjwIPfccw8pKSl88cUXfPrppyQlJREUFEReXh5hYWGEhISwfft2BgwYwHvvvccDDzxQ69dTyt2KSi0cPGUL8YMOh1yO51+86ivQ15trIltzXfd29GjfunIPPaptYJO4cKDZBX1TMWTIkEuu4f7f//1fVq5cCUBGRgYHDx68LOjj4uIYMGAAAIMGDeLo0aPVjn3HHXdUrvPxxx8DsHHjxsrxJ06cSGhoaLXbLlu2jAULFmCxWDh+/Dh79+5FROjYsSODBw8GoE0bW6PRdevW8ZOf/KTyEExYWFitr3vKlCkEBgYCthvZHn30UbZv3463tzcHDhyoHPeBBx4gKCjoknEfeugh3nvvPV599VU++ugjvv9eb5JWTUdxWQWH7IF+4NTFPfTMM8WV6/j5eHFNu9YMjQujR4dgekTaDrtEhwbi5eX+QK9Jswv6K+15N6ZWrVpVfr5+/XrWrVvH5s2bCQoKYsyYMdVe4+3vf/H4m7e3N8XFxZet47iet7c3FovF6ZqOHDnCK6+8QnJyMqGhocyePbtO15r7+PhgtVoBLtve8XW/9tprtG/fnh07dmC1WgkICLjiuNOmTav8y2TQoEGX/SJUqjFl5J1nU9ppNqflsi3jLOl557lw/6ivt9CtXWsSYkKZntjZFurtg4kJC8K7CQd6TZpd0LtDcHAwBQUFNS7Pz88nNDSUoKAg9u/fz5YtW2pct65GjhzJsmXL+NWvfsVXX33FmTNnLlvn3LlztGrVipCQEE6ePMkXX3zBmDFj6NmzJ8ePHyc5OZnBgwdTUFBAYGAg48eP56233mLs2LGVh27CwsKIjY0lNTWVSZMmsWLFiiu+7ujoaLy8vHj//fepqLB1txg/fjzz589n1qxZlxy6CQgIYMKECcybN6/GQ09KNZTj+cVsTstlc1oum9JyyTpr29GKaO3H4NgwpiZE2U+MtqZLeCt8vZvNbUa10qB3Qnh4OCNHjiQ+Pp5JkyZxyy23XLJ84sSJ/O1vf6N379707NmTYcOGubyG559/nnvuuYd//OMfDB8+nA4dOhAcHHzJOv379ychIYFevXrRuXNnRo4cCYCfnx8fffQRjz32GMXFxQQGBrJu3ToeeughDhw4QL9+/fD19WXOnDk8+uijPP/88zz44IP85je/YcyYMTXW9PDDDzNt2jQ++OADJk6cWLm3P3HiRLZv305iYiJ+fn7cfPPNvPTSSwDMmjWLlStXctNNN7n8PVLK0enCUrYctoX65rRcjpy2XTQQEujL8K7hzB3dlRHdwrkmsnWTOI7ekJpFr5t9+/bRu3dvN1XUNJSWluLt7Y2Pjw+bN29m3rx5lSeHm5NXXnmF/Px8XnzxxXqPpd8XytHZ82VsOZzHlsO2YP/hpO2v8Nb+PgyNC2N4t3CGdwund4c2Tfp4el1dqdeN7tE3E+np6dx9991YrVb8/Px4++233V3SVZs6dSppaWl8/fXX7i5FeYDCUgvJR/LYlHaaTWm57D1+DmMgwNeLwbFh3JbQiRHdIojv1AYfDzoMUxca9M1E9+7d2bZtm7vLqJcLVw0pVRfFZRWkHjtjO4F6OJedmflUWA1+3l4M7NKWn47rwYhrwukf3RY/n5Yd7FVp0CulmqRSSwXb08/ajrEfzmV7+lnKKqz4eAn9okOYd303hncLZ1CXUAJ8vd1dbpOmQa+UahIsFVZ2ZuVXXhmTciyPknIrIhDfKYQHRsYyrFs4g2PDaO2v0XU19N1SSrlFhdWw7/g5++WOp/n+SB5FZbZLdHt1COaeITEM7xrO0LhwQoL0SWL1oUGvlGoUxhgOniqsDPYth/PIL7Z1buzarhVTB0YxvGsEw7qGEd5Azb1aKqeCXkQmAn/G9szYd4wxL1dZ/how1j4ZBEQaY9ral1UAu+zL0o0xU1xQd5PXunVrCgsLyc7O5vHHH2f58uWXrTNmzBheeeUVEhOrvSIKgNdff525c+dWthNwpu2xUk2BMYb0vPNsSrt4LfvpQlvDr+jQQCb0ac/wbuGM6BZB+zZXvqta1U+tQS8i3sAbwHggE0gWkVXGmL0X1jHG/Mxh/ceABIchio0xA1xWcTPTqVOnakPeWa+//jr33ntvZdA70/a4KTHGYIzBy0uvgmgJLtx9eiHYL9x9Ghnsz6hrbKE+vFs4ncOC3Fxpy+LMT98Q4JAx5rAxpgxYCtx2hfXvAT50RXFNxVNPPcUbb7xROf3CCy/wyiuvUFhYyLhx4xg4cCB9+/bl008/vWzbo0ePEh8fD0BxcTEzZsygd+/eTJ069ZJeN/PmzSMxMZE+ffrw/PPPA7ZGadnZ2YwdO5axY21/MMXGxnL69GkAXn31VeLj44mPj+f111+v/Hq9e/dmzpw59OnTh5tuuqnanjqrV69m6NChJCQkcOONN3Ly5EkACgsLeeCBB+jbty/9+vWrbIHw5ZdfMnDgQPr378+4ceMueR8uiI+P5+jRoxw9epSePXty3333ER8fT0ZGRrWvD2ztk0eMGEH//v0ZMmQIBQUFjB49+pKbwUaNGsWOHTuc/N9Sjel0YSmf7czmmZW7uOGV9Qz//dc8uWwH6/adpF90CC/e1od1T15P0jPjeH1GAncP7qwh7wbOHLqJAjIcpjOBodWtKCJdgDjA8Y6YABFJASzAy8aYT6rZbi4wFyAmJubK1XzxFJzYdeV1rlaHvjDp5RoXT58+nZ/+9Kc88sgjgK1D5Jo1awgICGDlypW0adOG06dPM2zYMKZMmVLj7dR//etfCQoKYt++fezcuZOBAwdWLquuvfDjjz/Oq6++yjfffHNZ3/nU1FTee+89kpKSMMYwdOhQrr/+ekJDQ51qhzxq1Ci2bNmCiPDOO+/wxz/+kT/96U+8+OKLhISEsGuX7T0+c+YMOTk5zJkzhw0bNhAXF+dUO+ODBw/y/vvvV7aDuJr2yQ8++CB///vfef311zlw4AAlJSX079+/1q+pGl5+cTnf229S2pyWy/4Tl959OnNoDCO6RdCrQ7BH3n3aXLn6ZOwMYLkxpsJhXhdjTJaIdAW+FpFdxpg0x42MMQuABWBrgeDimuotISGBU6dOkZ2dTU5ODqGhoXTu3Jny8nKeeeYZNmzYgJeXF1lZWZw8eZIOHTpUO86GDRt4/PHHAejXrx/9+vWrXFZde2HH5VVt3LiRqVOnVvaXueOOO/j222+ZMmWKU+2QMzMzmT59OsePH6esrKyy5fK6detYunRp5XqhoaGsXr2a0aNHV67jTDvjLl26XNLz52raJ9911128+OKL/M///A8LFy5k9uzZtX491TDOl1lIPnrGfsnjaXZl5WM14O9ju/v0FxM6MaJbOH2jQlr83adNmTNBnwV0dpiOts+rzgzgEccZxpgs+7+HRWQ9tuP3aZdv6qQr7Hk3pLvuuovly5dz4sQJpk+fDsDixYvJyckhNTUVX19fYmNj69QW2FXthS9wph3yY489xpNPPsmUKVMqnx51tRzbGcOlLY0d2xlf7esLCgpi/PjxfPrppyxbtozU1NSrrk3VTamlgm0XblJKO832jLOUVxh8vYWEzqE8dkN3hncLJyGmLf4+epNSc+HMr+BkoLuIxImIH7YwX1V1JRHpBYQCmx3mhYqIv/3zCGAksLfqts3B9OnTWbp0KcuXL+euu+4CbG16IyMj8fX15ZtvvuHYsWNXHGP06NEsWbIEgN27d7Nz506g+vbCF9TUIvm6667jk08+4fz58xQVFbFy5Uquu+46p19Pfn4+UVFRALz//vuV88ePH3/J+YgzZ84wbNgwNmzYwJEjRwAqD93ExsZWPgpw69atlcurqun1ObZPBigoKKjsv//QQw/x+OOPM3jw4BofsqLqz1JhZVv6Gd745hD3vpNEvxe+YsaCLfzl64OUWaw8OKorH/zXEHY8fxPLfjKcn43vwbCu4RryzUyte/TGGIuIPAqswXZ55UJjzB4RmQ+kGGMuhP4MYKm5tB1mb+AtEbFi+6XysuPVOs1Jnz59KCgoICoqio4dOwK2lru33norffv2JTExkV69el1xjHnz5vHAAw/Qu3dvevfuzaBBg4Ca2wsDzJ07l4kTJ9KpUye++eabyvkDBw5k9uzZDBkyBLAFY0JCQo1PrarqhRde4K677iI0NJQbbrihMqSfffZZHnnkEeLj4/H29ub555/njjvuYMGCBdxxxx1YrVYiIyNZu3ZtZYviPn36MHToUHr06FHt17ra9smtW7dm0KBBtGnTRh832AAyz5xnzZ6TbDp0mqQjeRSW2n659uoQzKyhXRjeLZwhcWGEBOpNSp5C2xSrJik7O5sxY8awf//+Gi/N1O8L5508V8K/dh5n9c5stqWfBaBrRKvK69j1JqXmT9sUq2blgw8+4Ne//jWvvvqqXn9fD6cLS/li13FW7zxO8tE8jIHeHdvwiwk9mdyvI13CW9U+iPIIGvSqybnvvvu477773F1Gs3T2fBlf7j7BZzuPsyntNFYD10S25qfjejC5f0e6tWvt7hKVGzSboDfGePzjvpTzmtohR3c6V1LO2j0n+WxnNt8ePI3FaogND+LhMdcwuX9HerYP1p+dFq5ZBH1AQAC5ubmEh4frN6zCGENubi4BAS23P8r5Mgvr9p3isx3ZrD+QQ5nFSlTbQB4cFcet/TvRp1Mb/VlRlZpF0EdHR5OZmUlOTo67S1FNREBAANHR0e4uo1GVlFew/odTrN5xnH/vP0lJuZX2bfy5d2gXJvfvSELnthruqlrNIuh9fX0r78pUqiUptVTw7YHTfLYzm7V7T1JUVkFEaz/uGtSZyf06Mjg2TFsNqFo1i6BXqiUpr7CyKS2Xz3Zks2bPCc6VWGgb5Mut/TsxuV8nhnUN03YD6qpo0CvVBFRYDUlHcvls53G+2HWcM+fLCfb34aY+HZjcvyOjronAV8Nd1ZEGvVJuYrUatqafYfWObD7ffYKcglKC/Ly5sXd7JvfryOge7fSh18olNOiVakTGGHZk5vPZjmz+tes4x/NL8Pfx4oZekUzu14kbekUS6KfhrlxLg16pRpCRd54VWzNZuS2LY7nn8fUWru/Rjqcm9WJc7/a09tcfRdVw9LtLqQZSUFLO57uOsyI1i++P5iECI7tF8MjYa5jQp4M2DVONRoNeKReqsBq+O3SaFVszWbPnBCXlVrq2a8UvJvRkakIUndoGurtE1RRVWOD4Dig9B93Gunx4DXqlXODQqQKWp2bxybYsTpwrISTQlzsHRTNtYDQD9EYmVVWFBY5vh6MbbR/pm6GsECL7wMObXP7lNOiVqqMzRWWs3pnNitRMdmTm4+0ljOnRjuduvZZxvSP14Rzqoopy2x770W/twb7FFuwAET2h33SIHQVdRl55nDrSoFfqKpRXWPlm/ylWbM3k6/2nKK8w9O7Yhmdv6c1tA6JoF6w93RW2YM/efjHYM5IuBnu7XheDPXYUtI5s8HI06JWqhTGGPdnnWJ6ayaod2eQVlRHR2o/7hscybWA013Zq4+4SlbtVlEP2NodDMVugvMi2rF0v6D/j4h57IwR7VRr0StXg1LkSPtmexYrULH44WYCftxfjr23PtEFRXNe9nd6p2pJVBvuFQzFJDsHeGwbMdAj2du6tFSeDXkQmAn/G9szYd4wxL1dZ/hpw4VRxEBBpjGlrX3Y/8Kx92X8bY95HqSaqpLyCtXtPsmJrJhsO5GA1kBDTlv++PZ5b+3UiJEgviWyRLGWXBntGEpSfty2LvLbJBXtVtQa9iHgDbwDjgUwgWURWOT7k2xjzM4f1HwMS7J+HAc8DiYABUu3bnnHpq1CqHoyxtSJYnprFZzuzKSix0CkkgHljunHHwGh9KlNLZCmD7K32YP/u8mBPuPdisLeKcG+tTnBmj34IcMgYcxhARJYCtwF7a1j/HmzhDjABWGuMybNvuxaYCHxYn6KVcoXMM+f5eGsWH2/N5GjueQJ9vZkU34Fpg6IZ3jVc2/+2JJcEu/1QjKXYtiyyDyT8yCHYw91bax04E/RRQIbDdCYwtLoVRaQLEAd8fYVto6rZbi4wFyAmJsaJkpSqm6JSi+1u1a2ZbDmcB8CwrmE8MvYaJvXtqK0ImhJjoKIMLCVQXmL711IC5cVgKbUFsaXUPl1Sv/UKT10M9vbxMOh+W6g302CvytXf1TOA5caYiqvZyBizAFgAkJiYqA8DVS5ljCHpSB7LkjP4YvcJissriA0P4snxPZiaEEXnsCB3l9j0VZQ7BKRjcNqD1DE4XbHehWnqEQfefuATYPvwDbj4+YXpgBDw8QffQAgKhy4jbMEeFOayt62pcCbos4DODtPR9nnVmQE8UmXbMVW2Xe98eUrVXamlgtU7jrNw4xH2Hj9HsL8Ptyd0YtrAaAZ1CW05d6uWF0N+FpzLhHz7x7ksKDvvfDBf3b7bpbx8HAI20BauPhf+DbCFbNVl1QXzhW2uuF6g/XN/8NIb1i5wJuiTge4iEoctuGcAM6uuJCK9gFBgs8PsNcBLIhJqn74JeLpeFStVi9OFpSzeks4/thzjdGEpPdq35uU7+nJ7QpTn9Xe3WqHo1MUAr/zIuPj5+dNVNhLbtdx+rS/d2w1oe3kQ1yV8K6ft63nr4TB3q/V/wBhjEZFHsYW2N7DQGLNHROYDKcaYVfZVZwBLjTHGYds8EXkR2y8LgPkXTswq5Wr7T5xj4cYjfLI9mzKLlbE92/Ffo+IYdU1E8917Ly102AuvLsyzwFp+6TZ+rSGkM4REQacBEBJtn462fQR3Ah8/t7wc5R7ikMtNQmJioklJSXF3GaqZsFoN6w+c4t2NR/juUC4Bvl5MGxjNAyPjuCayiV8WWWGBwhOXB7fjdMnZS7cRb2jT6WJot4m6PMgDQqC5/mJTdSYiqcaYxOqW6d9UqlkqKrWwYmsm7313lCOni+jQJoBfTuzJzCExtA1qgnurJfmQ9jUcWge5afY99OzLj30HtL0Y2jHDLob3hY/WHfRQiLpq+h2jmpXss8W8v+koH36fzrkSC/2jQ/jzjAHc3Ldj02tJcPoQHPgSDq6BY5vAarEFeYe+tmuyHQO8TbTtUIt/sLurVh5Ig141C1vTz7Bw4xG+2H0CYwyT4jvyX6NiGRjThK6esZRB+iY4sMb2kZdmmx95LYx4DHpMhKhE3SNXjU6/41STZamw8sXuE7y78QjbM84SHODDg6PiuG94F6JDm8i174U5cPAr25572jdQVgDe/hA3GobNgx4ToK3eBKjcS4NeNTn558v5MDmdDzYdJTu/hNjwIH47pQ/TBkW7/85VY+DEzot77VmpgIHgjtB3mm2vPW40+LVyb51KOdCgV03G4ZxC3vvuKMtTMykur2B413Dm3xbP2F6ReLuz70xZERz+j+1Y+4GvoCAbEIgaBGN/bdtr79BXr3RRTZYGvXIrYwyb0nJ5d+MRvt5/Cj9vL6YM6MR/jYxz7wM9zhyzH5JZA0c2QEUp+AXDNTfY9tqvGd8k29EqVR0NeuUWJeUVrNqezcLvjrD/RAHhrfx4Ylx3Zg2LITI4oPELqrBAZrL9Kpmv4JS9OWtYNxj8kG2vPWa43mikmiUNetWoThWUsGhLOou3HCO3qIxeHYL54539mNK/U+O3JzifZ7u2/cCXtuvbi8/Y+rJ0GQETXoLuEyDimsatSakGoEGvGsWe7HwWbjzK6h3ZlFVYGdcrkgdHxTG8W3jjXR5pDOT8YAv2A2tsD5MwFRAUAT0mQY+boNsNtjtLlfIgGvSqQW3+IZul/97Mrow8WvnAE/ER3NYvkug2gPUgHN1nu5HIWmH/1/GjwtbH5ZLpqssdpiuq2/7C5/ZnfJ5NtxXWoS9c96Rtrz1qoHY6VB5Ng165njHkpSWz67M36XdmLX+WQvC3L/vB/uFKXj4OH97VTPva/o3sA6N+Zgv3kMuef6OUx9KgV65TdBrrjo84u+nvhBUeYJjx5Ui7MbQeNgVf/6AqAVxTKNcw7e1b/TripZc1KlULDXpVPxUWOLQWti3CemANXtZyMqxdWRX2KGOmzaNX52h3V6hUi6dBr+rm1H7Yvgh2fARFpyj0CWVp2XjWBYxn5q0Tub9fx6bTg0apFk6DXjmv+CzsXgHbF0NWKsbLhxORo3mleDCri/owc/g1LLipB20CfN1dqVLKgQa9ujKrFY6sh22LYf9ntueHRl7L6RHP8ezhPnx5tIL+0SF8PLUv8VF6WaJSTZEGvape3mHYvgS2f2h7hF1ACCTcS2n8Pfzfvta89Z/DBPgKL94ez8whMe7tRaOUuiKngl5EJgJ/xvbM2HeMMS9Xs87dwAuAAXYYY2ba51cAu+yrpRtjprigbtUQSgth76e2QzPHvgPEdgPRTfOh5y18k3aO5z7aTUbeSaYmRPHMzb1pF+xf67BKKfeqNehFxBt4AxgPZALJIrLKGLPXYZ3uwNPASGPMGRGJdBii2BgzwLVlK5cxBtI32w7N7P0EygohrCvc8Bvofw+ERJF9tpj5S/fw5Z4TdGvXiiVzhjKiW4S7K1dKOcmZPfohwCFjzGEAEVkK3AbsdVhnDvCGMeYMgDHmlKsLVS6Wnwk7PrQdnsk7DH6toc/tMOBe27NKRSivsPL3DYd5bd0BrMbwiwk9mXNdV/x8mtgj+5RSV+RM0EcBGQ7TmcDQKuv0ABCR77Ad3nnBGPOlfVmAiKQAFuBlY8wnVb+AiMwF5gLExOjTeBpMeYnthOr2xbanIWGgyygY/Qu49rZLHpaRcjSPZz/Zzf4TBYzrFckLU/rQOayJPNVJKXVVXHUy1gfoDowBooENItLXGHMW6GKMyRKRrsDXIrLLGJPmuLExZgGwACAxMdG4qCYFtkMz2Vtth2Z2L4eSfAjpDNf/0nZoJizuktXPFJXx8hf7+Sglg04hAbz1o0HcdG17vSZeqWbMmaDPAjo7TEfb5znKBJKMMeXAERE5gC34k40xWQDGmMMish5IANJQDav4DGxbZAv4nH3gEwC9p0DCLIgdDV6XHn6xWg3LUzP5/Rf7KCix8OPRXXl8XHdaufvRfUqpenPmpzgZ6C4icdgCfgYws8o6nwD3AO+JSAS2QzmHRSQUOG+MKbXPHwn80VXFq2qUFkDS32DT/9n23qMHw+TXIf6OGtvv7j9xjmdX7ibl2BkGx4by37f3pWeH4MatWynVYGoNemOMRUQeBdZgO/6+0BizR0TmAynGmFX2ZTeJyF6gAviFMSZXREYAb4mIFfDCdox+bw1fStVHeTEkvwsbX4XzudDzZhjzNHTsV+MmRaUW/vzvg7y78QhtAnz44539uHNgNF56TbxSHkWMaVqHxBMTE01KSoq7y2g+LGWw7QPY8AoUHIeuY22XRkYPqnETYwxr9pxk/uo9ZOeXcM+QzvxyQi9CW+lj8pRqrkQk1RiTWN0yPQDbXFVYYOdH8J+XbQ/TiBkO096B2FFX3Cwj7zzPr9rD1/tP0atDMP83cyCDuoQ2UtFKKXfQoG9urFbYuxK++T3kHoSOA2Dya9Bt3BX7spdZrLz97WH+7+uDeIvw7C29mT0iFh9vvSZeKU+nQd9cGAM/fAHf/A5O7oZ2vWH6Iug1udYHb2xKO81vPtlNWk4RN/ftwG8mX0vHkMBGKlwp5W4a9E2dMXD4G/j6vyEr1dae4I53bFfR1PKc05yCUl76fB8rt2URExbEew8MZmzPyCtuo5TyPBr0TdmxzbaAP7bRdpPTlP+D/jPBu/b/tq/2nOD//XMHpeVWHr/hGh4eew0BvvoAbKVaIg36pihrq+0QzaF10Lo9TPofGHQ/+DjXKXLltkx+/s+dxEeF8Nrd/enarnUDF6yUaso06JuSk3ttAb//MwgMhfHzYfAc8HO+x8yiLcf4zae7Gd41nLfvS9Q7W5VSGvRNQm4arP897FoO/sEw5hkYNg8C2lzVMG/9J43ff7GfG3tH8peZA/VQjVIK0KB3r7MZ8J8/2FoF+/jDqJ/CiMchKOyqhjHG8NraA/zv14eY3K8jr00fgK9eNqmUstOgd4eCE/DtnyD177bpIXNh1M8guP1VD2WMYf5ne3nvu6PMGNyZ303tq4/1U0pdQoO+MZ3Pg42vwfdvQ0UZJNxraxccEl2n4Sqshmc+3sVHKRk8OCqOZ2/pre2ElVKX0aBvDCX5sPlN2PyG7VF9/e6G638F4d3qPGSZxcqTy7bz2c7jPD6uOz+7sbuGvFKqWhr0DamsCJLegu/+DCVnbf3gx/4aInvVa9iS8goeXryVr/ef4pmbezF3dN1/YSilPJ8GfUMoL7Edf//2T1B0CrrfZAv4TgPqPXRRqYWH3k9hy5Fcfjc1nllDu9R7TKWUZ9Ogd7XTB+EfUyE/A2Kvg+n/sD1s2wXyz5cz++/fszMzn9fuHsDtCVEuGVcp5dk06F2pohw+nmM7ZHPfp9B1jMuGziko5UfvJnE4p4g3Zw1kQp8OLhtbKeXZNOhdacMrkL0N7v7ApSGffbaYe99J4nh+Ce/OTuS67u1cNrZSyvNp0LtKVips+B/oNwOuvc1lwx7LLWLm20mcKy7ngweHMDj26m6mUkopp26fFJGJIvKDiBwSkadqWOduEdkrIntEZInD/PtF5KD9435XFd6klBfDxz+G4A4w6Q8uG/bAyQLu+ttmzpdZ+HDuMA15pVSd1LpHLyLewBvAeCATSBaRVY4P+RaR7sDTwEhjzBkRibTPDwOeBxIBA6Tatz3j+pfiRut+a3va048+gcC2LhlyZ+ZZ7lv4PX7eXiz78XC6tw92ybhKqZbHmT36IcAhY8xhY0wZsBSoemxiDvDGhQA3xpyyz58ArDXG5NmXrQUmuqb0JuLwfyDprzDkx9BtrEuG/P5IHjPfTqK1vw/LfzJCQ14pVS/OBH0UkOEwnWmf56gH0ENEvhORLSIy8Sq2RUTmikiKiKTk5OQ4X727leTDJw9DeHe48QWXDPmfAznctzCJ9m38+edPhhMT7nyLYqWUqo6rTsb6AN2BMUA0sEFE+jq7sTFmAbAAIDEx0biopob3xa+g4Dg8uPaqesbX5Mvdx3nsw210jwzmgweHENHauQeNKKXUlTizR58FdHaYjrbPc5QJrDLGlBtjjgAHsAW/M9s2T3tXwY4PYfTPIXpQvYf7eGsmjyzZRt+oED6cO0xDXinlMs4EfTLQXUTiRMQPmAGsqrLOJ9j25hGRCGyHcg4Da4CbRCRUREKBm+zzmrfCU/DZT6Fjfxj9i3oP948tx3hy2Q6GxoXxjweHEhLoW/8alVLKrtZDN8YYi4g8ii2gvYGFxpg9IjIfSDHGrOJioO8FKoBfGGNyAUTkRWy/LADmG2PyGuKFNBpjYNXjUFoIUxeAd/1C+W//SeNlfSqUUqoBiTFN65B4YmKiSUlJcXcZNdu2CD59BCa8BMMfqfMwxhj+9NUB/vLNIW7t34lX7+6vT4VSStWZiKQaYxKrW6Z3xl6NM8fgi6dszcqGzqvzMFar7alQf9+kT4VSSjU8DXpnWa3wiT3cb38TvOq2911hNTz98U6WpWTqU6GUUo1Cg95ZW96EY9/BbW9C25g6DVFmsfKzj7bzr136VCilVOPRoHfGqX3w7/nQ8xYYMLNOQ+hToZRS7qJBXxtLGXw8F/yD4dY/Qx32wAtLLTz0fjJJR/J4aWpfZg6t218ESilVFxr0tdnwRzixE2YsgdZX3wf+7Pky7n8vmd1Z+lQopZR7aNBfSUay7bmvA2ZBr1uuenN9KpRSqinQoK9J2XlY+WNoEwUTf3/Vm2edLeZH+lQopVQToEFfk3XPQ14a3L8aAkKuatOjp4uY9Y7tqVD/eHAIifrAEKWUG2nQVyfta/h+AQx7GOJGX9WmJ/JLuOutzVgqrHw4dxjxUVf3S0IppVxNg76q4jPwySMQ0RPGPXfVm3+w+Si5haV8/sR19OrQpgEKVEqpq6NBX9Xnv4SiU3DPEvANvKpNyyxWlqVkMK53ew15pVSToV20HO1ZCbuWwehfQqeEq958zZ4TnC4sY5ZeJ6+UakI06C8oOAGfPQmdBsJ1T9ZpiEVbjtE5LJDReoWNUqoJ0aCHiz3my8/D1Lfq1GP+0KkCko7kMXNIF7y0E6VSqgnRY/QAWz+Ag2tg0h+hXY86DbFoSzq+3sLdidEuLk4ppepH9+jzjsCaZyDuehg8p05DFJdVsGJrJpPiOxKuz3pVSjUxLTvorRW2HvPiXa8e86t3ZlNQYtGTsEqpJsmpZBORiSLyg4gcEpGnqlk+W0RyRGS7/eMhh2UVDvOrPlTcvTb/BdI3w81/hJC6H3JZvOUY3SNbMyRO74BVSjU9tR6jFxFv4A1gPJAJJIvIKmPM3iqrfmSMebSaIYqNMQPqXamrndwDX/839L4V+k2v8zC7MvPZkZnPC7deqw8RUUo1Sc7s0Q8BDhljDhtjyoClwG0NW1YDs5TBxz+GgLYw+fU69Zi/YHHSMQJ9vbljkJ6EVUo1Tc4EfRSQ4TCdaZ9X1TQR2Skiy0Wks8P8ABFJEZEtInJ7PWp1nfW/h5O7YMr/QquIOg9zrqScT7dnM6V/J9oEXP0lmUop1RhcdTJ2NRBrjOkHrAXed1jWxRiTCMwEXheRy56hJyJz7b8MUnJyclxUUg3Sk+C71yHhR9BzUr2GWrk1i+LyCu4d1sU1tSmlVANwJuizAMc99Gj7vErGmFxjTKl98h1gkMOyLPu/h4H1wGW9BYwxC4wxicaYxHbtGvCu0tJCW4/5kGiY8FK9hjLGsDjpGP2iQ+gbrR0qlVJNlzNBnwx0F5E4EfEDZgCXXD0jIh0dJqcA++zzQ0XE3/55BDASqHoSt/GsfQ7OHIXb/wYB9Ws6lnLsDAdOFuollUqpJq/Wq26MMRYReRRYA3gDC40xe0RkPpBijFkFPC4iUwALkAfMtm/eG3hLRKzYfqm8XM3VOo3j0DpIeRdGPAaxI+s93KItxwgO8OHW/p1cUJxSSjUcp1ogGGM+Bz6vMu85h8+fBp6uZrtNQN961lh/5/Pg00ehXW8Y+2y9h8stLOWLXSeYOTSGID/tIqGUatpaRkp9/nMoyoGZH4FvQL2H+2dqJmUVVj1so5RqFjy/BcKu5bB7BYx5Cjr2r/dwVqthSVI6Q+LC6N4+2AUFKqVUw/LsoD93HP71/yB6MIz8mUuG/PbQadLzzusllUqpZsNzg94YWPUoVJTZe8y75ijV4i3HCG/lx4Q+7V0ynlJKNTTPDfrU92xX2oyfD+GX3aNVJ8fzi/n3/lPcldgZfx9vl4yplFINzTODPjcN1vwauo6FwQ/Vvr6Tln6fgdUYZg7Rk7BKqebD84LeWgErf2J7HOBtb9SrYZkjS4WVpcnpjO7ejpjwIJeMqZRSjcHzgv67P0Pm93DznyCkut5rdbNu3ylOnivVk7BKqWbHs4L+xC745iXoMxX63unSoRcnHaNjSABjezZgLx6llGoAnhP0llJbj/mgMLjlVZcdsgE4llvEtwdPc8+QGHy8PectU0q1DJ6TWgXHwVoOU/5iC3sXWpKUjreXMH1w59pXVkqpJsZzWiCExsK8TbaTsC5UaqlgWUoG43u3p32b+rdPUEqpxuY5e/Tg8pAH+GLXCc6cL9eTsEqpZsuzgr4BLE46Rmx4ECO6hbu7FKWUqhMN+ivYf+IcyUfPMGtoF7y8XHdyVymlGpMG/RUsSUrHz8eLOwdFu7sUpZSqMw36GhSVWvh4axaT+3YktJWfu8tRSqk606Cvwaod2RSWWpg1TPvaKKWaN6eCXkQmisgPInJIRJ6qZvlsEckRke32j4cclt0vIgftH/e7sviGYoxh0ZZj9OoQzMCYUHeXo5RS9VLrdfQi4g28AYwHMoFkEVlVzUO+PzLGPFpl2zDgeSARMECqfdszLqm+gezIzGdP9jlevD0eceEdtkop5Q7O7NEPAQ4ZYw4bY8qApcBtTo4/AVhrjMmzh/taYGLdSm08i7ccI8jPm9sHdHJ3KUopVW/OBH0UkOEwnWmfV9U0EdkpIstF5EKvAGe3bTLyz5ezemc2tydEERzg+huwlFKqsbnqZOxqINYY0w/bXvv7V7OxiMwVkRQRScnJyXFRSXWzYmsmJeVWZg3Vk7BKKc/gTNBnAY7dvKLt8yoZY3KNMaX2yXeAQc5ua99+gTEm0RiT2K6d+9oAG2NYnHSMhJi29OkU4rY6lFLKlZwJ+mSgu4jEiYgfMANY5biCiHR0mJwC7LN/vga4SURCRSQUuMk+r0nacjiPtJwiZg3VvjZKKc9R61U3xhiLiDyKLaC9gYXGmD0iMh9IMcasAh4XkSmABcgDZtu3zRORF7H9sgCYb4zJa4DX4RKLk44REujL5H4da19ZKaWaCafaFBtjPgc+rzLvOYfPnwaermHbhcDCetTYKHIKSlmz5wT3DY8lwNfb3eUopZTL6J2xdstSMiivMMzUk7BKKQ+jQQ9UWA1LktIZ0S2cbu1au7scpZRyKQ16YMOBHLLOFutJWKWUR9Kgx3YStl2wPzf1ae/uUpRSyuVafNBnnS3m6/2nmJ7YGV/vFv92KKU8UItPtqXfp2OAGUM617quUko1Ry066MsrrCxNzuCGnpFEhwa5uxyllGoQLTro1+49SU5BqT5cRCnl0Vp00C/acoyotoFc3yPS3aUopVSDabFBn5ZTyKa0XGYOjcHbSx8uopTyXC026D9MSsfHS7g7UU/CKqU8W4sM+pLyCv6ZmsmE+A60C/Z3dzlKKdWgWmTQ/2vncfKLy/XhIkqpFqFFBv2ipGN0bdeK4V3D3V2KUko1uBYX9Huy89mWfpZZQ7sgoidhlVKer8UF/ZKkdPx9vLhzYLS7S1FKqUbRooK+sNTCJ9uyuLV/J0KCfN1djlJKNYoWFfSfbMuiqKyCe4dpO2KlVMvhVNCLyEQR+UFEDonIU1dYb5qIGBFJtE/HikixiGy3f/zNVYVfLWMMi7Yco0+nNvSPDnFXGUop1ehqfWasiHgDbwDjgUwgWURWGWP2VlkvGHgCSKoyRJoxZoBryq27reln2X+igJem9tWTsEqpFsWZPfohwCFjzGFjTBmwFLitmvVeBP4AlLiwPpdZvOUYrf19uG1AJ3eXopRSjcqZoI8CMhymM+3zKonIQKCzMeZf1WwfJyLbROQ/InJd3UutuzNFZXy26zhTE6Jo5V/rHzFKKeVR6p16IuIFvArMrmbxcSDGGJMrIoOAT0SkjzHmXJUx5gJzAWJiXH+36oqtmZRZrNqOWCnVIjmzR58FOHb+irbPuyAYiAfWi8hRYBiwSkQSjTGlxphcAGNMKpAG9Kj6BYwxC4wxicaYxHbt2tXtldTAajUsTkonsUsovTq0cenYSinVHDgT9MlAdxGJExE/YAaw6sJCY0y+MSbCGBNrjIkFtgBTjDEpItLOfjIXEekKdAcOu/xVXMHmw7kcOV2kl1QqpVqsWg/dGGMsIvIosAbwBhYaY/aIyHwgxRiz6gqbjwbmi0g5YAV+YozJc0Xhzlq05RihQb5MjO/QmF9WKaWaDKeO0RtjPgc+rzLvuRrWHePw+QpgRT3qq5eT50r4au9JHhwVR4Cvt7vKUEopt/LoO2M/Ss6gwmqYOURPwiqlWi6PDXpLhZUPv0/nuu4RxEa0cnc5SinlNh4b9Ot/yOF4fgmzhupJWKVUy+axQb8o6Rjt2/hzY+9Id5eilFJu5ZFBn5F3nv8cyGHG4Bh8vD3yJSqllNM8MgWXfJ+OlwgzhnSufWWllPJwHhf0ZRYry5IzGNcrko4hge4uRyml3M7jgv7LPSfILSpjlt4Jq5RSgAcG/eItx4gJC+K6ayLcXYpSSjUJHhX0h04VkHQkj5lDY/Dy0oeLKKUUeFjQL9qSjp+3F3cNinZ3KUop1WR4TNAXl1WwYmsmk/p2ILy1v7vLUUqpJsNjgv5cSTnX92in7YiVUqoKj3muXvs2Afxl5kB3l6GUUk2Ox+zRK6WUqp4GvVJKeTgNeqWU8nAa9Eop5eGcCnoRmSgiP4jIIRF56grrTRMRIyKJDvOetm/3g4hMcEXRSimlnFfrVTci4g28AYwHMoFkEVlljNlbZb1g4AkgyWHetcAMoA/QCVgnIj2MMRWuewlKKaWuxJk9+iHAIWPMYWNMGbAUuK2a9V4E/gCUOMy7DVhqjCk1xhwBDtnHU0op1UicCfooIMNhOtM+r5KIDAQ6G2P+dbXbKqWUalj1vmFKRLyAV4HZ9RhjLjDXPlkoIj/Uo6QI4HQ9tvck+l5cSt+PS+n7cZEnvBc1tgVwJuizAMdHNUXb510QDMQD60UEoAOwSkSmOLEtAMaYBcACJ2qplYikGGMSa1/T8+l7cSl9Py6l78dFnv5eOHPoJhnoLiJxIuKH7eTqqgsLjTH5xpgIY0ysMSYW2AJMMcak2NebISL+IhIHdAe+d/mrUEopVaNa9+iNMRYReRRYA3gDC40xe0RkPpBijFl1hW33iMgyYC9gAR7RK26UUqpxiTHG3TW4lIjMtR8KavH0vbiUvh+X0vfjIk9/Lzwu6JVSSl1KWyAopZSH06BXSikP5zFB72w/npZARDqLyDcisldE9ojIE+6uyd1ExFtEtonIZ+6uxd1EpK2ILBeR/SKyT0SGu7smdxKRn9l/TnaLyIciEuDumlzNI4LeoR/PJOBa4B57n52WygL8P2PMtcAw4JEW/n6ArQ/TPncX0UT8GfjSGNML6E8Lfl9EJAp4HEg0xsRju7Jwhnurcj2PCHqc78fTIhhjjhtjtto/L8D2g9xiW0+ISDRwC/COu2txNxEJAUYD7wIYY8qMMWfdWpT7+QCBIuIDBAHZbq7H5Twl6LWnTg1EJBZIwKGraAv0OvBLwOrmOpqCOCAHeM9+KOsdEWnl7qLcxRiTBbwCpAPHgXxjzFfurcr1PCXoVTVEpDWwAvipMeacu+txBxGZDJwyxqS6u5YmwgcYCPzVGJMAFAEt9pyWiIRi++s/Dlsr9VYicq97q3I9Twl6p3rqtCQi4ost5BcbYz52dz1uNBKYIiJHsR3Su0FEFrm3JLfKBDKNMRf+wluOLfhbqhuBI8aYHGNMOfAxMMLNNbmcpwT9FfvxtDRi6y73LrDPGPOqu+txJ2PM08aYaHsfphnA18YYj9tjc5Yx5gSQISI97bPGYWtR0lKlA8NEJMj+czMODzw5Xe82xU1BTf143FyWO40EfgTsEpHt9nnPGGM+d19Jqgl5DFhs3yk6DDzg5nrcxhiTJCLLga3Yrlbbhos66TYl2gJBKaU8nKcculFKKVUDDXqllPJwGvRKKeXhNOiVUsrDadArpZSH06BXSikPp0GvlFIe7v8DzUndfb+JIzIAAAAASUVORK5CYII=\n"
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    }
  ]
}